## iBASE MASTER CONFIG FILE

{
    "albumRoot" : "/path/to/pictures",
    "dbfile"    : "./iBase.db",
    "logfile"   : "./iBase.log",
    "loglevel"  : "ERROR",
    "results"   : 10,

    # Configuration for the ollama server
    "llmHost"  : "localhost:11434",
    "llmModel" : "gemma3:12b",
    "llmTries" : 3,
    
    # Not sure if this will ever be used 
    # in-program, but it's here for tracking.
    "VERSION"  : "1.1.0"
}
